# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookstore.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62ookstore.proto\x12\tbookstore\"N\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\x12\r\n\x05stock\x18\x04 \x01(\x05\x12\r\n\x05price\x18\x05 \x01(\x01\"!\n\x10\x42ookTopicRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"\x1f\n\x11ItemNumberRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"Q\n\rBookListReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1e\n\x05\x62ooks\x18\x03 \x03(\x0b\x32\x0f.bookstore.Book\"P\n\rBookInfoReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1d\n\x04\x62ook\x18\x03 \x01(\x0b\x32\x0f.bookstore.Book\"0\n\x0c\x42uyBookReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\nHelloReply\x12\x15\n\rhello_message\x18\x01 \x01(\t2\x8d\x02\n\tBookStore\x12\x39\n\x05Hello\x12\x17.bookstore.HelloRequest\x1a\x15.bookstore.HelloReply\"\x00\x12\x41\n\x06Search\x12\x1b.bookstore.BookTopicRequest\x1a\x18.bookstore.BookListReply\"\x00\x12\x42\n\x06Lookup\x12\x1c.bookstore.ItemNumberRequest\x1a\x18.bookstore.BookInfoReply\"\x00\x12>\n\x03\x42uy\x12\x1c.bookstore.ItemNumberRequest\x1a\x17.bookstore.BuyBookReply\"\x00\x42\x43ZAcs.williams.edu/cs339-s23/23jml8-24ys5/bookstore/client-go/proto/b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookstore_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZAcs.williams.edu/cs339-s23/23jml8-24ys5/bookstore/client-go/proto/'
  _BOOK._serialized_start=30
  _BOOK._serialized_end=108
  _BOOKTOPICREQUEST._serialized_start=110
  _BOOKTOPICREQUEST._serialized_end=143
  _ITEMNUMBERREQUEST._serialized_start=145
  _ITEMNUMBERREQUEST._serialized_end=176
  _BOOKLISTREPLY._serialized_start=178
  _BOOKLISTREPLY._serialized_end=259
  _BOOKINFOREPLY._serialized_start=261
  _BOOKINFOREPLY._serialized_end=341
  _BUYBOOKREPLY._serialized_start=343
  _BUYBOOKREPLY._serialized_end=391
  _HELLOREQUEST._serialized_start=393
  _HELLOREQUEST._serialized_end=421
  _HELLOREPLY._serialized_start=423
  _HELLOREPLY._serialized_end=458
  _BOOKSTORE._serialized_start=461
  _BOOKSTORE._serialized_end=730
# @@protoc_insertion_point(module_scope)
